### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by micheljung** [pircbotx/pircbotx#289]
Last release is over 2 years ago

**Comment by TheLQ** [comment]
https://github.com/TheLQ/pircbotx/wiki/ChangeLog
https://github.com/TheLQ/pircbotx/commits/master

There has been lots of progress since the 2.0 release, its just my time to tackle the big jobs has gone down. But Ive been thinking recently about releasing the current master as 2.1 just so people have a non snapshot to work with, which will definetly help

Patches always welcome

**Comment by micheljung** [comment]
I've been waiting for 2.1 for almost one year, so yes, please :-) "Release early, release often"

**Comment by TheLQ** [comment]
I just released 2.1. I apologize for the long wait

**Comment by micheljung** [comment]
Great, thank you for your efforts! Really appreciate it :-)
