### ISSUE TITLE
ModeEvent issue

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#302]
Everytime somebody sets +b something or -b something to a channel, a ModeEvent is raised reporting channel modes (e.g. +nt). Is this the normal behaviour? Any way to disable it?

My IRC client isn't showing it everytime somebody puts or remove a ban so I tought it can be an issue.

**Comment by Cypherke** [comment]
Since a ban is a channel mode it's normal ModeEvent gets triggered. If you want to watch for bans and not other modes, it seems better to use   onSetChannelBan(SetChannelBanEvent event)  and  onRemoveChannelBan(RemoveChannelBanEvent event) as mentioned here: http://thelq.github.io/pircbotx/latest/apidocs/org/pircbotx/hooks/events/ModeEvent.html

**Comment by MyWay** [comment]
I'm saying something different: you place a ban and you get modes of the
channel on the next message, e.g. +nt, instead you should get only +b mask.

**Comment by hoerup** [comment]
Please be aware that a +b with pircbotx2.1 gives you 2 different ModeEvent's:
First comes the +b mode event, but when the target channel gets a raw mode that contains space (such as a +b mask) then it sends out a new MODE command to server, which then generates the second ModeEvent containg the current modes for the channel
