### ISSUE TITLE
getChannelSource() in NoticeEvent sending back bot nick when Channel is null 

### ISSUE THREAD

**Issue by jztech101** [pircbotx/pircbotx#348]

**Comment by hoerup** [comment]
Could you please provide more details ? When does this happen? Which IRC network? Which PircbotX version?

**Comment by jztech101** [comment]
Latest and freenode. As for when this happens, it happens when the channel is null.

**Comment by Cypherke** [comment]
When the Channel is null, we are the target of the notice as per definition in the getChannel(). (see [this](https://github.com/pircbotx/pircbotx/blob/6d77deb94fef15f5120a523f18b61cab9785623a/src/main/java/org/pircbotx/hooks/events/NoticeEvent.java#L57) )
And since channelSource is the raw target string, it is our nickname... maybe ChannelSources isnt the right name for that variable, i agree, but I'd label this as "working as intended".

See [this](https://github.com/pircbotx/pircbotx/blob/6d77deb94fef15f5120a523f18b61cab9785623a/src/main/java/org/pircbotx/InputParser.java#L491) for checking how the line is parsed.
