### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by hoerup** [pircbotx/pircbotx#381]
Pircbotx 2.x has a performance regression compared to 1.9
Is noticable when the bot joins many channels with lots of people joining and leaving constantly  (think 20 channels with average 100 users each)

2.x is so slow that it's unusable so I needed to use a older bot using pircbotx 1.9

**Comment by jenga201** [comment]
This is probably because of snapshots, which are expensive.

Could you try changing your config?
[setSnapshotsEnabled(false)](http://pircbotx.github.io/pircbotx/latest/apidocs/org/pircbotx/Configuration.Builder.html#setSnapshotsEnabled-boolean-)

From what I understand of snapshots, they give the ability to clone the UserChannelDao, the Channel, and the User objects.

Snapshots are enabled by default and is called when the PartEvent, QuitEvent, or DisconnectEvent is triggered. (InputParser.processCommand())

The [getDaoSnapshot](http://pircbotx.github.io/pircbotx/latest/apidocs/org/pircbotx/hooks/events/DisconnectEvent.html#getDaoSnapshot--) methods are deprecated, but the [getUserChannelDaoSnapshot](http://pircbotx.github.io/pircbotx/latest/apidocs/org/pircbotx/hooks/events/DisconnectEvent.html#getDaoSnapshot--) methods are not.
I'm thinking these were meant to be removed at some point.



If that has no consequences except improving performance, we could;
Remove SnapshotsEnabled parameter
Remove getDaoSnapshot and getUserChannelDaoSnapshot methods from those Events
Remove the automatic snapshot generation in InputParser.java

This would still allow users to manually create snapshots using the various [createSnapshot](http://pircbotx.github.io/pircbotx/latest/apidocs/org/pircbotx/UserChannelDao.html#createSnapshot--) methods.

**Comment by hoerup** [comment]
#386 and #387 improves the concurrency
