### ISSUE TITLE
v2.3 is missing on the central repository

### ISSUE THREAD

**Issue by NotMyFault** [pircbotx/pircbotx#411]
Hey,

I'm currently in the process of updating an older project and noticed version 2.3 is tagged on GitHub, but the release is missing on the central repository: https://repo1.maven.org/maven2/org/pircbotx/pircbotx/

Could the release get deployed to mavencentral please?

Thanks in advance!

**Comment by Cypherke** [comment]
As per our wiki, we dont upload to maven any more. ( https://github.com/pircbotx/pircbotx/wiki/Downloads )
The latest release on jitpack: https://jitpack.io/#pircbotx/pircbotx/master-SNAPSHOT

**Comment by NotMyFault** [comment]
> we dont upload to maven any more

Very unfortunate to hear, sounds like I have to stay on 2.1 then. Based on prior incidents, JitPack does not provide suitable resources for my needs, noticeable by outages (to an extent to have third parties complain about it) and malfunction deployments. 2.3 not existing as release tag on https://jitpack.io/#pircbotx/pircbotx is a prime example.

Anyway, thanks for looking into it.

**Comment by timja** [comment]
The failure there doesn't look to be related to reliability.

It's because they use an old version of maven by default:

> Detected Maven Version: 3.6.1 is not in the allowed range 3.8.

Which it looks like is being experimented with in https://github.com/pircbotx/pircbotx/commit/ced83dd2c88af33d21ab1802df4a488074726a47

this should be enough but maybe it's not working for you for some reason:
```
sdk install maven 3.8.6
```

FWIW in my org we have used Jitpack extensively the last year or two and we've found it fine (although we do mirror it at CI level to alleviate any upstream issues).
